export interface AudioManifestItem {
  filename: string;
  title: string;
  description: string;
  author: string;
  category: string;
  tags: string[];
  estimatedDuration?: number; // Optional estimated duration
}

// Static require for each audio file (bundler limitation)
export const audioModules = {
  'te_pego_hasta_que_adelgaci.mp3': require('../../assets/audios/te_pego_hasta_que_adelgaci.mp3'),
  'test-audio.mp3': require('../../assets/audios/test-audio.mp3'),
  'accidente_grave.mp3': require('../../assets/audios/accidente_grave.mp3'),
  'ayerrrrrrrr.mp3': require('../../assets/audios/ayerrrrrrrr.mp3'),
  'beso_la_guagua.mp3': require('../../assets/audios/beso_la_guagua.mp3'),
  'conchetumareee.mp3': require('../../assets/audios/conchetumareee.mp3'),
  'estoy_que_le_pego_un_martillazo_a_la_wea.mp3': require('../../assets/audios/estoy_que_le_pego_un_martillazo_a_la_wea.mp3'),
  'guadalaraja.mp3': require('../../assets/audios/guadalaraja.mp3'),
  'hablai_mai.mp3': require('../../assets/audios/hablai_mai.mp3'),
  'hoy_lanzo_y_meto.mp3': require('../../assets/audios/hoy_lanzo_y_meto.mp3'),
  'los_postres.mp3': require('../../assets/audios/los_postres.mp3'),
  'martillazo.mp3': require('../../assets/audios/martillazo.mp3'),
  'me_comi_un_hoyo_mas_feo_que_la_ctm.mp3': require('../../assets/audios/me_comi_un_hoyo_mas_feo_que_la_ctm.mp3'),
  'me_lanzo_meto_menso_me_meto.mp3': require('../../assets/audios/me_lanzo_meto_menso_me_meto.mp3'),
  'no_vai_a_comparar_el_yugi.mp3': require('../../assets/audios/no_vai_a_comparar_el_yugi.mp3'),
  'que_wea_pagaste_el_plan.mp3': require('../../assets/audios/que_wea_pagaste_el_plan.mp3'),
  'sapos_culiaos.mp3': require('../../assets/audios/sapos_culiaos.mp3'),
  'sapos_culiaos_(short).mp3': require('../../assets/audios/sapos_culiaos_(short).mp3'),
  'saque_la_polera.mp3': require('../../assets/audios/saque_la_polera.mp3'),
  'toy_que_le_pego_un_combo_en_locico_a_la_wea.mp3': require('../../assets/audios/toy_que_le_pego_un_combo_en_locico_a_la_wea.mp3'),
  'ultra_venosa.mp3': require('../../assets/audios/ultra_venosa.mp3'),
  'uno_ataca_al_dino.mp3': require('../../assets/audios/uno_ataca_al_dino.mp3'),
  'y_lo_mato_el_otro_weon.mp3': require('../../assets/audios/y_lo_mato_el_otro_weon.mp3'),
  'y_lo_mato_el_otro_weon_(short).mp3': require('../../assets/audios/y_lo_mato_el_otro_weon_(short).mp3'),
  'yeiyeye_te_amo.mp3': require('../../assets/audios/yeiyeye_te_amo.mp3'),
  'Untitled_video_-_Made_with_Clipchamp.mp3': require('../../assets/audios/Untitled_video_-_Made_with_Clipchamp.mp3'),
  'a_vo_que_te_gusta_tocar_guitarra.mp3': require('../../assets/audios/a_vo_que_te_gusta_tocar_guitarra.mp3'),
  'aaah_guaton_culiaoo.mp3': require('../../assets/audios/aaah_guaton_culiaoo.mp3'),
  'andai_igual_que_el_meins.mp3': require('../../assets/audios/andai_igual_que_el_meins.mp3'),
  'audio_del_dota.mp3': require('../../assets/audios/audio_del_dota.mp3'),
  'chao_feo_culiao_shao_shao.mp3': require('../../assets/audios/chao_feo_culiao_shao_shao.mp3'),
  'chavo1.mp3': require('../../assets/audios/chavo1.mp3'),
  'chavo2.mp3': require('../../assets/audios/chavo2.mp3'),
  'dile_que_se_vaya_pa_la_casa.mp3': require('../../assets/audios/dile_que_se_vaya_pa_la_casa.mp3'),
  'enviando_tik_tok.mp3': require('../../assets/audios/enviando_tik_tok.mp3'),
  'he_cagao_de_una_manera.mp3': require('../../assets/audios/he_cagao_de_una_manera.mp3'),
  'hola_queridos_hermanos.mp3': require('../../assets/audios/hola_queridos_hermanos.mp3'),
  'juega_como_el_pico_invoker.mp3': require('../../assets/audios/juega_como_el_pico_invoker.mp3'),
  'juega_menos_dota.mp3': require('../../assets/audios/juega_menos_dota.mp3'),
  'la_secadora.mp3': require('../../assets/audios/la_secadora.mp3'),
  'me_dice_lokita.mp3': require('../../assets/audios/me_dice_lokita.mp3'),
  'oe_que_te_pasa_vieja_ctm_que_andai_sapiando.mp3': require('../../assets/audios/oe_que_te_pasa_vieja_ctm_que_andai_sapiando.mp3'),
  'picas_de_comida.mp3': require('../../assets/audios/picas_de_comida.mp3'),
  'que_te_pasa_obeso_ctm.mp3': require('../../assets/audios/que_te_pasa_obeso_ctm.mp3'),
  'queatee_callao_un_rato.mp3': require('../../assets/audios/queatee_callao_un_rato.mp3'),
  'queridos_creyentes.mp3': require('../../assets/audios/queridos_creyentes.mp3'),
  'risita_guaton.mp3': require('../../assets/audios/risita_guaton.mp3'),
  'se_amurra_hasta_pa_jugar_a_la_pelota.mp3': require('../../assets/audios/se_amurra_hasta_pa_jugar_a_la_pelota.mp3'),
  'ta_weno_el_eish.mp3': require('../../assets/audios/ta_weno_el_eish.mp3'),
  'te_fuiste_del_dota.mp3': require('../../assets/audios/te_fuiste_del_dota.mp3'),
  'tecito_de_hoja.mp3': require('../../assets/audios/tecito_de_hoja.mp3'),
  'toy_en_la_pega.mp3': require('../../assets/audios/toy_en_la_pega.mp3'),
  'toy_terminando_el_dota.mp3': require('../../assets/audios/toy_terminando_el_dota.mp3'),
  'una_taza_de_arroz.mp3': require('../../assets/audios/una_taza_de_arroz.mp3'),
  'vay_a_puro_lavar_el_auto.mp3': require('../../assets/audios/vay_a_puro_lavar_el_auto.mp3'),
  'yo_no_tengo_la_cuenta_de_mi_clave.mp3': require('../../assets/audios/yo_no_tengo_la_cuenta_de_mi_clave.mp3'),
  'yo_robo_un_dia.mp3': require('../../assets/audios/yo_robo_un_dia.mp3'),
  'yo_si_cocino,_antes_me_bañaban.mp3': require('../../assets/audios/yo_si_cocino,_antes_me_bañaban.mp3'),
};

export const audioManifest: AudioManifestItem[] = [
  {
    filename: 'te_pego_hasta_que_adelgaci.mp3',
    title: 'Te Pego Hasta Que Adelgaci',
    description: 'Local audio file from repository (MP3 format for iOS compatibility)',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'repository', 'mp3'],
    estimatedDuration: 5, // 5 seconds
  },
  {
    filename: 'test-audio.mp3',
    title: 'Test Audio',
    description: 'Test audio file for debugging audio functionality',
    author: 'Test Artist',
    category: 'Test',
    tags: ['test', 'audio', 'debug', 'mp3'],
    estimatedDuration: 3, // 3 seconds
  },
  {
    filename: 'accidente_grave.mp3',
    title: 'Accidente Grave',
    description: 'Audio clip about a serious accident',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'accident', 'mp3'],
    estimatedDuration: 4,
  },
  {
    filename: 'ayerrrrrrrr.mp3',
    title: 'Ayerrrrrrrr',
    description: 'Audio clip with extended pronunciation',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'pronunciation', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'beso_la_guagua.mp3',
    title: 'Beso La Guagua',
    description: 'Audio clip about kissing the bus',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'bus', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'conchetumareee.mp3',
    title: 'Conchetumareee',
    description: 'Audio clip with extended expression',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'expression', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'estoy_que_le_pego_un_martillazo_a_la_wea.mp3',
    title: 'Estoy Que Le Pego Un Martillazo A La Wea',
    description: 'Audio clip about hitting something with a hammer',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'hammer', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'guadalaraja.mp3',
    title: 'Guadalaraja',
    description: 'Audio clip about Guadalajara',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'city', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'hablai_mai.mp3',
    title: 'Hablai Mai',
    description: 'Audio clip about speaking',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'speech', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'hoy_lanzo_y_meto.mp3',
    title: 'Hoy Lanzo Y Meto',
    description: 'Audio clip about launching and entering',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'action', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'los_postres.mp3',
    title: 'Los Postres',
    description: 'Audio clip about desserts',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'dessert', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'martillazo.mp3',
    title: 'Martillazo',
    description: 'Audio clip about a hammer hit',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'hammer', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'me_comi_un_hoyo_mas_feo_que_la_ctm.mp3',
    title: 'Me Comi Un Hoyo Mas Feo Que La CTM',
    description: 'Audio clip about eating a hole',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'hole', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'me_lanzo_meto_menso_me_meto.mp3',
    title: 'Me Lanzo Meto Menso Me Meto',
    description: 'Audio clip about launching and entering',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'action', 'mp3'],
    estimatedDuration: 4,
  },
  {
    filename: 'no_vai_a_comparar_el_yugi.mp3',
    title: 'No Vai A Comparar El Yugi',
    description: 'Audio clip about not comparing to Yugi',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'comparison', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'que_wea_pagaste_el_plan.mp3',
    title: 'Que Wea Pagaste El Plan',
    description: 'Audio clip about paying for a plan',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'payment', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'sapos_culiaos.mp3',
    title: 'Sapos Culiaos',
    description: 'Audio clip about frogs',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'frogs', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'sapos_culiaos_(short).mp3',
    title: 'Sapos Culiaos (Short)',
    description: 'Short audio clip about frogs',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'frogs', 'short', 'mp3'],
    estimatedDuration: 1,
  },
  {
    filename: 'saque_la_polera.mp3',
    title: 'Saque La Polera',
    description: 'Audio clip about taking off a shirt',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'clothing', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'toy_que_le_pego_un_combo_en_locico_a_la_wea.mp3',
    title: 'Toy Que Le Pego Un Combo En Locico A La Wea',
    description: 'Audio clip about hitting with a combo',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'combo', 'mp3'],
    estimatedDuration: 4,
  },
  {
    filename: 'ultra_venosa.mp3',
    title: 'Ultra Venosa',
    description: 'Audio clip about something ultra venous',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'venous', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'uno_ataca_al_dino.mp3',
    title: 'Uno Ataca Al Dino',
    description: 'Audio clip about attacking a dinosaur',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'dinosaur', 'mp3'],
    estimatedDuration: 5,
  },
  {
    filename: 'y_lo_mato_el_otro_weon.mp3',
    title: 'Y Lo Mato El Otro Weon',
    description: 'Audio clip about someone being killed',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'action', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'y_lo_mato_el_otro_weon_(short).mp3',
    title: 'Y Lo Mato El Otro Weon (Short)',
    description: 'Short audio clip about someone being killed',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'action', 'short', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'yeiyeye_te_amo.mp3',
    title: 'Yeiyeye Te Amo',
    description: 'Audio clip about love',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'love', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'Untitled_video_-_Made_with_Clipchamp.mp3',
    title: 'Untitled Video - Made with Clipchamp',
    description: 'Audio from a video created with Clipchamp',
    author: 'Clipchamp',
    category: 'Video',
    tags: ['video', 'audio', 'clipchamp', 'mp3'],
    estimatedDuration: 6,
  },
  // New audio files added
  {
    filename: 'a_vo_que_te_gusta_tocar_guitarra.mp3',
    title: 'A Vo Que Te Gusta Tocar Guitarra',
    description: 'Audio clip about liking to play guitar',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'guitar', 'music', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'aaah_guaton_culiaoo.mp3',
    title: 'Aaah Guaton Culiaoo',
    description: 'Audio clip with expression about weight',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'expression', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'andai_igual_que_el_meins.mp3',
    title: 'Andai Igual Que El Meins',
    description: 'Audio clip about being similar to someone',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'comparison', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'audio_del_dota.mp3',
    title: 'Audio Del Dota',
    description: 'Audio clip about Dota game',
    author: 'Local Artist',
    category: 'Gaming',
    tags: ['gaming', 'audio', 'dota', 'mp3'],
    estimatedDuration: 4,
  },
  {
    filename: 'chao_feo_culiao_shao_shao.mp3',
    title: 'Chao Feo Culiao Shao Shao',
    description: 'Audio clip saying goodbye',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'goodbye', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'chavo1.mp3',
    title: 'Chavo 1',
    description: 'First Chavo audio clip',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'chavo', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'chavo2.mp3',
    title: 'Chavo 2',
    description: 'Second Chavo audio clip',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'chavo', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'dile_que_se_vaya_pa_la_casa.mp3',
    title: 'Dile Que Se Vaya Pa La Casa',
    description: 'Audio clip about telling someone to go home',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'home', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'enviando_tik_tok.mp3',
    title: 'Enviando Tik Tok',
    description: 'Audio clip about sending TikTok',
    author: 'Local Artist',
    category: 'Social Media',
    tags: ['social', 'audio', 'tiktok', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'he_cagao_de_una_manera.mp3',
    title: 'He Cagao De Una Manera',
    description: 'Audio clip with expression',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'expression', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'hola_queridos_hermanos.mp3',
    title: 'Hola Queridos Hermanos',
    description: 'Audio clip greeting dear brothers',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'greeting', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'juega_como_el_pico_invoker.mp3',
    title: 'Juega Como El Pico Invoker',
    description: 'Audio clip about playing Invoker poorly',
    author: 'Local Artist',
    category: 'Gaming',
    tags: ['gaming', 'audio', 'dota', 'invoker', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'juega_menos_dota.mp3',
    title: 'Juega Menos Dota',
    description: 'Audio clip about playing less Dota',
    author: 'Local Artist',
    category: 'Gaming',
    tags: ['gaming', 'audio', 'dota', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'la_secadora.mp3',
    title: 'La Secadora',
    description: 'Audio clip about the dryer',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'appliance', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'me_dice_lokita.mp3',
    title: 'Me Dice Lokita',
    description: 'Audio clip about being called crazy',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'nickname', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'oe_que_te_pasa_vieja_ctm_que_andai_sapiando.mp3',
    title: 'Oe Que Te Pasa Vieja CTM Que Andai Sapiando',
    description: 'Audio clip asking what\'s wrong',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'question', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'picas_de_comida.mp3',
    title: 'Picas De Comida',
    description: 'Audio clip about food pieces',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'food', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'que_te_pasa_obeso_ctm.mp3',
    title: 'Que Te Pasa Obeso CTM',
    description: 'Audio clip asking what\'s wrong with obese person',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'question', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'queatee_callao_un_rato.mp3',
    title: 'Queatee Callao Un Rato',
    description: 'Audio clip about being quiet for a while',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'quiet', 'mp3'],
    estimatedDuration: 4,
  },
  {
    filename: 'queridos_creyentes.mp3',
    title: 'Queridos Creyentes',
    description: 'Audio clip addressing dear believers',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'believers', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'risita_guaton.mp3',
    title: 'Risita Guaton',
    description: 'Audio clip with fat person\'s laugh',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'laugh', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'se_amurra_hasta_pa_jugar_a_la_pelota.mp3',
    title: 'Se Amurra Hasta Pa Jugar A La Pelota',
    description: 'Audio clip about being lazy even to play ball',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'lazy', 'sports', 'mp3'],
    estimatedDuration: 4,
  },
  {
    filename: 'ta_weno_el_eish.mp3',
    title: 'Ta Weno El Eish',
    description: 'Audio clip about something being good',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'good', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'te_fuiste_del_dota.mp3',
    title: 'Te Fuiste Del Dota',
    description: 'Audio clip about leaving Dota game',
    author: 'Local Artist',
    category: 'Gaming',
    tags: ['gaming', 'audio', 'dota', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'tecito_de_hoja.mp3',
    title: 'Tecito De Hoja',
    description: 'Audio clip about leaf tea',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'tea', 'mp3'],
    estimatedDuration: 4,
  },
  {
    filename: 'toy_en_la_pega.mp3',
    title: 'Toy En La Pega',
    description: 'Audio clip about being at work',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'work', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'toy_terminando_el_dota.mp3',
    title: 'Toy Terminando El Dota',
    description: 'Audio clip about finishing Dota game',
    author: 'Local Artist',
    category: 'Gaming',
    tags: ['gaming', 'audio', 'dota', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'una_taza_de_arroz.mp3',
    title: 'Una Taza De Arroz',
    description: 'Audio clip about a cup of rice',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'food', 'rice', 'mp3'],
    estimatedDuration: 2,
  },
  {
    filename: 'vay_a_puro_lavar_el_auto.mp3',
    title: 'Vay A Puro Lavar El Auto',
    description: 'Audio clip about going to wash the car',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'car', 'wash', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'yo_no_tengo_la_cuenta_de_mi_clave.mp3',
    title: 'Yo No Tengo La Cuenta De Mi Clave',
    description: 'Audio clip about not having password account',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'password', 'account', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'yo_robo_un_dia.mp3',
    title: 'Yo Robo Un Dia',
    description: 'Audio clip about stealing one day',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'steal', 'mp3'],
    estimatedDuration: 3,
  },
  {
    filename: 'yo_si_cocino,_antes_me_bañaban.mp3',
    title: 'Yo Si Cocino, Antes Me Bañaban',
    description: 'Audio clip about cooking and being bathed before',
    author: 'Local Artist',
    category: 'Local',
    tags: ['local', 'audio', 'cooking', 'bath', 'mp3'],
    estimatedDuration: 3,
  },
];

// Helper function to get audio file by filename
export const getAudioByFilename = (filename: string): AudioManifestItem | undefined => {
  return audioManifest.find(item => item.filename === filename);
};

// Helper function to get all audio files
export const getAllAudioFiles = (): AudioManifestItem[] => {
  return [...audioManifest];
};
